# Generated by Django 5.0.4 on 2024-05-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(db_column='product_id')),
                ('delivery_id', models.BigIntegerField(db_column='delivery_id')),
                ('quantity', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Goods_receipt',
                'managed': False,
            },
        ),
    ]
